Use --pipe option with modern systemd-nspawn

diff --git a/systemd-nspawn-renew-root-password b/systemd-nspawn-renew-root-password
--- a/systemd-nspawn-renew-root-password
+++ b/systemd-nspawn-renew-root-password
@@ -2,7 +2,7 @@
 #
 #  nspawn-renew-root-password - renew root password for a container
 #
-#  Copyright (C) 2017, 2018, 2019 Alexander Yermolenko
+#  Copyright (C) 2017, 2018, 2019, 2021 Alexander Yermolenko
 #  <yaa.mbox@gmail.com>
 #
 #  This program is free software: you can redistribute it and/or modify
@@ -67,8 +67,17 @@ require pwgen
 
 password=`pwgen --secure 15`
 
-echo "root:$password" | systemd-nspawn $common_nspawn_options -D "$droot" chpasswd \
-    || die "Cannot set root password"
+systemd_version=$( systemd-nspawn --version | awk 'FNR==1 {print $2}' )
+echo "systemd-nspawn version: $systemd_version"
+
+if [ $systemd_version -gt 241 ]
+then
+    echo "root:$password" | systemd-nspawn $common_nspawn_options -D "$droot" --pipe chpasswd \
+        || die "Cannot set root password"
+else
+    echo "root:$password" | systemd-nspawn $common_nspawn_options -D "$droot" chpasswd \
+        || die "Cannot set root password"
+fi
 
 echo "New root password for $droot: $password"
 
