Check if the required tools are present

diff --git a/systemd-nspawn-helper b/systemd-nspawn-helper
--- a/systemd-nspawn-helper
+++ b/systemd-nspawn-helper
@@ -3,7 +3,7 @@
 #  nspawn-helper - shell script template for automating systemd-nspawn
 #  containers setup and usage
 #
-#  Copyright (C) 2017 Alexander Yermolenko <yaa.mbox@gmail.com>
+#  Copyright (C) 2017, 2018 Alexander Yermolenko <yaa.mbox@gmail.com>
 #
 #  This program is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -77,6 +77,13 @@ info()
     echo "INFO: $msg" 1>&2
 }
 
+require()
+{
+    local cmd=${1:?"Command name is required"}
+    local extra_info=${2:+"\nNote: $2"}
+    hash $cmd 2>/dev/null || die "$cmd not found$extra_info"
+}
+
 echo "machine_name=$machine_name"
 echo "distro_codename=$distro_codename"
 echo "distro_arch=$distro_arch"
@@ -102,6 +109,13 @@ fi
 echo "common_nspawn_options=$common_nspawn_options"
 
 [ "$EUID" -eq 0 ] || die "Superuser privileges required"
+
+require systemd-nspawn "apt-get install systemd-container"
+require debootstrap "apt-get install debootstrap"
+require runuser "apt-get install util-linux"
+require Xephyr "apt-get install xserver-xephyr"
+require xauth "apt-get install xauth"
+require bindfs "apt-get install bindfs"
 
 if [[ ! -e "$droot" ]]; then
     mkdir -p "$droot" || die "Cannot create $droot"
